Repository PyO3/maturin, pull requests merged in 2022-10, with the labels that each got.

#1168 Replace `pretty_env_logger` with `tracing-subscriber`
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: dependencies

#1170 Include `Cargo.lock` by default in source distribution
  Changelog.md
  src/module_writer.rs
  src/source_distribution.rs
  tests/run.rs
Labels: sdist

#1171 Release v0.13.6
  Cargo.lock
  Cargo.toml
  Changelog.md
  deny.toml
Labels: release

#1107 Build platform independent rust binary wheel through wasi
  .cirrus.yml
  .github/workflows/test.yml
  Changelog.md
  src/build_context.rs
  src/module_writer.rs
  src/target.rs
  test-crates/cargo-mock/src/main.rs
  test-crates/hello-world/check_installed/check_installed.py
  test-crates/hello-world/src/bin/foo.rs
  tests/common/integration.rs
  tests/common/mod.rs
  tests/run.rs
Labels: bindings/bin, target/wasm, target/wasi

#1187 Fix sdist build failure when using python first `src` layout
  .gitignore
  src/source_distribution.rs
  tests/run.rs
Labels: sdist

#1198 Fix sdist build for maturin itself
  src/source_distribution.rs
Labels: sdist

#1200 Remove support for specifying python package metadata in `Cargo.toml`
  src/cargo_toml.rs
  src/metadata.rs
  src/project_layout.rs
Labels: breaking-change

#1227 Remove `workspace.members` in `Cargo.toml` from sdist if there isn't any path dependency
  Cargo.toml
  Changelog.md
  MANIFEST.in
  README.md
  ci/build_deb.sh
  guide/src/index.md
  guide/src/project_layout.md
  setup.py
  src/metadata.rs
  src/project_layout.rs
  src/source_distribution.rs
  test-crates/hello-world/Cargo.toml
  test-crates/pyo3-ffi-pure/README.md
  test-crates/pyo3-ffi-pure/pyproject.toml
  test-crates/pyo3-mixed-py-subdir/Cargo.toml
  test-crates/pyo3-mixed-py-subdir/README.md
  test-crates/pyo3-mixed-submodule/Cargo.toml
  test-crates/pyo3-mixed-submodule/README.md
  test-crates/pyo3-pure/Cargo.lock
  test-crates/pyo3-pure/Cargo.toml
  test-crates/pyo3-pure/README.md
  test-crates/pyo3-pure/local-test/Cargo.toml
  test-crates/pyo3-pure/local-test/src/lib.rs
  test-crates/pyo3-pure/pyproject.toml
  test-crates/update_readme.py
  tests/common/other.rs
  tests/run.rs
Labels: sdist

#1229 Fix auditwheel libpython check on Python 3.7 and older versions
  Changelog.md
  src/auditwheel/audit.rs
Labels: wheel
