Repository PyO3/maturin, pull requests merged in 2022-11, with the labels that each got.

#1214 Configure bors
  .github/bors.toml
  .github/workflows/test.yml
  test-crates/pyo3-mixed-py-subdir/Cargo.lock
  test-crates/pyo3-mixed-py-subdir/Cargo.toml
  tests/run.rs
Labels: CI-no-fail-fast

#1232 Use generic tags when `sys.implementation.name` != `platform.python_implementation()`
  Changelog.md
  src/build_options.rs
  src/python_interpreter/get_interpreter_metadata.py
  src/python_interpreter/mod.rs
  sysconfig/pyston-3.8.txt
Labels: wheel

#1255 Add `[tool.maturin.include]` and `[tool.maturin.exclude]`
  Changelog.md
  README.md
  guide/src/distribution.md
  guide/src/metadata.md
  src/build_context.rs
  src/lib.rs
  src/module_writer.rs
  src/pyproject_toml.rs
  src/source_distribution.rs
  test-crates/pyo3-mixed-include-exclude/Cargo.lock
  test-crates/pyo3-mixed-include-exclude/Cargo.toml
  test-crates/pyo3-mixed-include-exclude/README.md
  test-crates/pyo3-mixed-include-exclude/check_installed/check_installed.py
  test-crates/pyo3-mixed-include-exclude/pyo3_mixed_include_exclude/.gitignore
  test-crates/pyo3-mixed-include-exclude/pyo3_mixed_include_exclude/__init__.py
  test-crates/pyo3-mixed-include-exclude/pyo3_mixed_include_exclude/exclude_this_file
  test-crates/pyo3-mixed-include-exclude/pyo3_mixed_include_exclude/include_this_file
  test-crates/pyo3-mixed-include-exclude/pyo3_mixed_include_exclude/python_module/__init__.py
  test-crates/pyo3-mixed-include-exclude/pyo3_mixed_include_exclude/python_module/double.py
  test-crates/pyo3-mixed-include-exclude/pyproject.toml
  test-crates/pyo3-mixed-include-exclude/src/lib.rs
  test-crates/pyo3-mixed-include-exclude/tests/test_pyo3_mixed_include_exclude.py
  test-crates/pyo3-mixed-include-exclude/tox.ini
  tests/common/other.rs
  tests/run.rs
Labels: sdist, wheel

#1258 Add sysconfig info for PyPy on ppc64le
  src/python_interpreter/sysconfig-linux.json
  sysconfig/pypy-linux-ppc64le-3.7-7.3.txt
  sysconfig/pypy-linux-ppc64le-3.8-7.3.txt
  sysconfig/pypy-linux-ppc64le-3.9-7.3.txt
Labels: PyPy, wheel, cross-compile

#1259 Ignore sdist tar ball instead of error out
  Changelog.md
  src/auditwheel/audit.rs
  src/build_context.rs
  src/build_options.rs
  src/cargo_toml.rs
  src/compile.rs
  src/main.rs
  src/module_writer.rs
  src/source_distribution.rs
Labels: sdist

#1263 Add support for `PYO3_ENVIRONMENT_SIGNATURE`
  .config/nextest.toml
  Cargo.lock
  src/compile.rs
  src/python_interpreter/mod.rs
  tests/run.rs
Labels: bindings/pyo3

#1269 Query macOS deployment target version from rustc
  src/compile.rs
  src/target.rs
Labels: wheel

#1270 auditwheel: allow bin bindings to link to libpython
  src/auditwheel/audit.rs
  src/build_context.rs
Labels: wheel, bindings/bin

#1275 Add support for `uniffi` bindings
  .config/nextest.toml
  Cargo.lock
  Cargo.toml
  Changelog.md
  README.md
  guide/src/bindings.md
  src/build_context.rs
  src/build_options.rs
  src/compile.rs
  src/main.rs
  src/module_writer.rs
  src/new_project.rs
  src/templates/Cargo.toml.j2
  src/templates/build.rs.j2
  src/templates/example.udl.j2
  src/templates/lib.rs.j2
  test-crates/uniffi-mixed/.gitignore
  test-crates/uniffi-mixed/Cargo.lock
  test-crates/uniffi-mixed/Cargo.toml
  test-crates/uniffi-mixed/build.rs
  test-crates/uniffi-mixed/check_installed/check_installed.py
  test-crates/uniffi-mixed/pyproject.toml
  test-crates/uniffi-mixed/src/lib.rs
  test-crates/uniffi-mixed/src/math.udl
  test-crates/uniffi-mixed/test_uniffi_mixed.py
  test-crates/uniffi-mixed/uniffi_mixed/__init__.py
  test-crates/uniffi-pure/Cargo.lock
  test-crates/uniffi-pure/Cargo.toml
  test-crates/uniffi-pure/build.rs
  test-crates/uniffi-pure/check_installed/check_installed.py
  test-crates/uniffi-pure/pyproject.toml
  test-crates/uniffi-pure/src/lib.rs
  test-crates/uniffi-pure/src/math.udl
  test-crates/uniffi-pure/test_uniffi_pure.py
  tests/cmd/build.stdout
  tests/cmd/develop.stdout
  tests/cmd/init.stdout
  tests/cmd/new.stdout
  tests/cmd/publish.stdout
  tests/run.rs
Labels: bindings/uniffi

#1278 Use `uniffi.toml` config file if it exist
  .config/nextest.toml
  .github/workflows/test.yml
  src/module_writer.rs
  test-crates/uniffi-pure/uniffi.toml
Labels: bindings/uniffi

#1273 Add `manylinux_2_34` and `manylinux_2_35` policies
  src/auditwheel/manylinux-policy.json
Labels: wheel

#1264 Release v0.14.0
  Cargo.lock
  Cargo.toml
  Changelog.md
  guide/src/develop.md
  guide/src/distribution.md
  test-crates/update_readme.py
Labels: release

#1288 Fix generating pep517 sdist for src-layout
  .github/workflows/test.yml
  Cargo.lock
  Changelog.md
  src/compile.rs
  src/main.rs
Labels: sdist

#1291 Deprecate `python-source` option in Cargo.toml
  Changelog.md
  README.md
  guide/src/project_layout.md
  src/develop.rs
  src/project_layout.rs
  test-crates/pyo3-mixed-py-subdir/Cargo.toml
  test-crates/pyo3-mixed-py-subdir/pyproject.toml
Labels: sdist

#1292 Fix auditwheel with read-only libraries
  Changelog.md
  src/build_context.rs
Labels: wheel

#1295 Update wasmtime dependency version to 3.0.0
  src/build_context.rs
  tests/run.rs
Labels: bindings/bin

#1296 Release v0.14.2
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release

#1299 Fix build error when required features of bin target isn't enabled
  Changelog.md
  src/compile.rs
Labels: bindings/bin

#1301 Fix wrong platform tag when building in i386 docker container on x86_64 host
  Changelog.md
  src/target.rs
Labels: wheel

#1303 Fix wrong platform tag when building in armv7 docker container on aarch64 host
  Changelog.md
  src/target.rs
Labels: wheel
