Repository PyO3/maturin, pull requests merged in 2022-12, with the labels that each got.

#1315 Release v0.14.3
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release

#1329 Release v0.14.4
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release

#1333 Build with `--no-default-features` by default when bootstrapping from sdist
  Changelog.md
  setup.py
Labels: distros-packaging, breaking-change

#1343 Fix sdist when all Cargo workspace members are excluded
  Changelog.md
  src/source_distribution.rs
Labels: sdist

#1345 Release v0.14.5
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release

#1348 Update normpath to 1.0.0
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust

#1347 Allow Rust crate to be placed outside of the directory containing `pyproject.toml`
  Changelog.md
  src/project_layout.rs
  src/source_distribution.rs
Labels: sdist

#1352 Run `uniffi-bindgen` command instead of depending on `uniffi_bindgen` crates
  .cirrus.yml
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  Changelog.md
  deny.toml
  guide/src/bindings.md
  src/module_writer.rs
  test-crates/with-data/check_installed/check_installed.py
  tests/run.rs
Labels: breaking-change, bindings/uniffi

#1353 Disallow uniffi bin bindings
  src/build_options.rs
Labels: bindings/bin, bindings/uniffi

#1358 Clarify `--interpreter` value
  guide/src/develop.md
  guide/src/distribution.md
  src/build_options.rs
  tests/cmd/build.stdout
  tests/cmd/publish.stdout
Labels: documentation

#1359 0.14: update `uniffi_bindgen` to 0.22.0
  Cargo.lock
  Cargo.toml
  test-crates/uniffi-mixed/Cargo.lock
  test-crates/uniffi-mixed/Cargo.toml
  test-crates/uniffi-pure/Cargo.lock
  test-crates/uniffi-pure/Cargo.toml
Labels: dependencies, rust

#1362 Add workspace lock file to sdist as a fallback
  Changelog.md
  src/source_distribution.rs
  tests/run.rs
Labels: sdist

#1363 Update cargo-xwin to 0.13.3
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust

#1366 Release v0.14.7
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release

#1373 Update `toml_edit` to 0.16.0
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust

#1375 Update cargo-zigbuild to 0.14.3
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust

#1379 Update `console` to 0.15.3
  Cargo.lock
  Cargo.toml
  deny.toml
Labels: dependencies, rust

#1378 Add support for packaging multiple pure Python packages
  Changelog.md
  guide/src/metadata.md
  src/module_writer.rs
  src/project_layout.rs
  src/pyproject_toml.rs
  src/source_distribution.rs
  test-crates/pyo3-mixed-src/pyproject.toml
  tests/run.rs
Labels: configuration

#1382 Release v0.14.8
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release
