Repository PyO3/maturin, pull requests merged in 2023-11, with the labels that each got.

#1828 use file_name to get bindings manifest name
  Cargo.lock
  Cargo.toml
  src/source_distribution.rs
  test-crates/pyo3-mixed-workspace/README.md
  test-crates/pyo3-mixed-workspace/check_installed/check_installed.py
  test-crates/pyo3-mixed-workspace/pyproject.toml
  test-crates/pyo3-mixed-workspace/rust/Cargo.lock
  test-crates/pyo3-mixed-workspace/rust/Cargo.toml
  test-crates/pyo3-mixed-workspace/rust/pyo3-mixed-workspace/Cargo.toml
  test-crates/pyo3-mixed-workspace/rust/pyo3-mixed-workspace/src/lib.rs
  test-crates/pyo3-mixed-workspace/rust/python/pyo3-mixed-workspace-py/Cargo.toml
  test-crates/pyo3-mixed-workspace/rust/python/pyo3-mixed-workspace-py/src/lib.rs
  test-crates/pyo3-mixed-workspace/src/pyo3_mixed_workspace/__init__.py
  test-crates/pyo3-mixed-workspace/src/pyo3_mixed_workspace/python_module/__init__.py
  test-crates/pyo3-mixed-workspace/src/pyo3_mixed_workspace/python_module/double.py
  test-crates/pyo3-mixed-workspace/src/tests/test_pyo3_mixed.py
  test-crates/pyo3-mixed-workspace/tox.ini
  tests/run.rs
Labels: CI-no-fail-fast, sdist

#1841 Fix rewriting workspace Cargo.toml in sdist
  src/source_distribution.rs
Labels: sdist

#1849 Add sdist tests for well-known downstream repositories
  .github/workflows/downstream.yml
  .github/workflows/test.yml
Labels: sdist

#1851 Release v1.3.2
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release

#1862 Update `cargo-options` to 0.7.1
  Cargo.lock
  Cargo.toml
  guide/src/develop.md
  guide/src/distribution.md
  src/build_options.rs
  src/develop.rs
  src/main.rs
  tests/cmd/build.stdout
  tests/cmd/develop.stdout
  tests/cmd/publish.stdout
Labels: dependencies, rust

#1865 Add support for cross compiling with `cross`
  .gitignore
  Cargo.lock
  Cargo.toml
  src/compile.rs
  src/project_layout.rs
Labels: cross-compile
