Repository PyO3/maturin, pull requests merged in 2023-08, with the labels that each got.

#1718 Release v1.2.0
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release

#1728 Handle renamed Rust dependency in sdist
  src/source_distribution.rs
Labels: sdist

#1731 Update wasmtime dependency version to 11.0
  src/build_context.rs
  tests/run.rs
Labels: target/wasi

#1733 Fix invalid TOML when rewriting workspace inherited dependencies
  src/source_distribution.rs
Labels: sdist

#1734 Release v1.2.1
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release

#1739 fix: preserve workspace inherited dependencies when building binary
  src/source_distribution.rs
Labels: sdist
