Repository PyO3/maturin, pull requests merged in 2023-06, with the labels that each got.

#1645 Add basic support for GraalPy
  README.md
  guide/src/bindings.md
  guide/src/platform_support.md
  src/build_context.rs
  src/build_options.rs
  src/compile.rs
  src/python_interpreter/config.rs
  src/python_interpreter/get_interpreter_metadata.py
  src/python_interpreter/mod.rs
  tests/run.rs
Labels: GraalPy

#1655 Update pep508_rs to 0.2.1
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust

#1660 Release v1.1.0
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release

#1661 Upgrade goblin to 0.7.1
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust

#1663 Upgrade rustls to 0.21
  Cargo.lock
  Cargo.toml
  src/upload.rs
Labels: dependencies, rust

#1666 Update cargo-zigbuild to 0.16.11
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust

#1683 Update uniffi to 0.24.1
  .cirrus.yml
  .github/workflows/test.yml
  guide/src/bindings.md
  src/templates/Cargo.toml.j2
  test-crates/uniffi-mixed/Cargo.lock
  test-crates/uniffi-mixed/Cargo.toml
  test-crates/uniffi-pure/Cargo.lock
  test-crates/uniffi-pure/Cargo.toml
Labels: bindings/uniffi
