Repository PyO3/maturin, pull requests merged in 2023-02, with the labels that each got.

#1439 Update `toml_edit` to 0.19 and switch back to `toml` for parsing
  Cargo.lock
  Cargo.toml
  deny.toml
  src/cargo_toml.rs
  src/metadata.rs
  src/module_writer.rs
  src/pyproject_toml.rs
Labels: dependencies, rust

#1454 Update `cargo-options` to 0.6.0
  Cargo.lock
  Cargo.toml
  src/build_options.rs
Labels: dependencies, rust

#1455 Update `zip` to 0.6.4
  Cargo.lock
  Cargo.toml
  src/module_writer.rs
Labels: dependencies, rust

#1466 Fix new `cargo deny` errors
  Cargo.lock
Labels: dependencies, rust

#1471 Raise an error when `Cargo.toml` contains removed python package metadata
  Changelog.md
  src/cargo_toml.rs
  src/project_layout.rs
Labels: breaking-change

#1474 Update cargo-zigbuild to 0.16.0
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust

#1476 Use extension_name instead of module_name for CFFI extensions in develop mode
  Changelog.md
  src/module_writer.rs
Labels: bindings/cffi

#1477 Release v0.14.13
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  Changelog.md
Labels: release

#1478 Update thread_local to 1.1.7 and minijina to 0.30.3
  Cargo.lock
Labels: dependencies, rust

#1479 Enable `extension-module` feature in `pyproject.toml` in project templates
  Cargo.lock
  guide/src/tutorial.md
  src/templates/Cargo.toml.j2
  src/templates/pyproject.toml.j2
Labels: bindings/pyo3, bindings/rust-cpython, configuration

#1481 Add support for uniffi 0.23
  .cirrus.yml
  .github/workflows/test.yml
  Changelog.md
  guide/src/bindings.md
  src/templates/Cargo.toml.j2
  src/templates/build.rs.j2
  src/templates/lib.rs.j2
  test-crates/uniffi-mixed/Cargo.lock
  test-crates/uniffi-mixed/Cargo.toml
  test-crates/uniffi-mixed/build.rs
  test-crates/uniffi-mixed/src/lib.rs
  test-crates/uniffi-pure/Cargo.lock
  test-crates/uniffi-pure/Cargo.toml
  test-crates/uniffi-pure/build.rs
  test-crates/uniffi-pure/src/lib.rs
Labels: bindings/uniffi

#1482 Release v1.0.0-beta.1
  Cargo.lock
  Cargo.toml
  src/pyproject_toml.rs
  src/templates/pyproject.toml.j2
Labels: release

#1484 Add support for Emscripten in `generate-ci` command
  Changelog.md
  src/ci.rs
  tests/cmd/generate-ci.stdout
Labels: target/emscripten

#1491 Use default `ext_suffix` for Emscripten target if not provided in `PYO3_CONFIG_FILE`
  Changelog.md
  src/python_interpreter/config.rs
  src/target.rs
Labels: target/emscripten

#1331 Upgrade keyring to 2.0.0
  Cargo.lock
  Cargo.toml
  deny.toml
  src/upload.rs
Labels: dependencies, rust

#1492 Backport and release v0.14.14
  Cargo.lock
  Cargo.toml
  Changelog.md
  guide/src/tutorial.md
  src/build_context.rs
  src/build_options.rs
  src/ci.rs
  src/module_writer.rs
  src/project_layout.rs
  src/python_interpreter/config.rs
  src/python_interpreter/mod.rs
  src/target.rs
  src/templates/Cargo.toml.j2
  src/templates/pyproject.toml.j2
  src/upload.rs
  test-crates/pyo3-abi3-without-version/Cargo.lock
  test-crates/pyo3-bin/Cargo.lock
  test-crates/pyo3-feature/Cargo.lock
  test-crates/pyo3-ffi-pure/Cargo.lock
  test-crates/pyo3-ffi-pure/Cargo.toml
  test-crates/pyo3-mixed-include-exclude/Cargo.lock
  test-crates/pyo3-mixed-py-subdir/Cargo.lock
  test-crates/pyo3-mixed-src/rust/Cargo.lock
  test-crates/pyo3-mixed-submodule/Cargo.lock
  test-crates/pyo3-mixed/Cargo.lock
  test-crates/pyo3-no-extension-module/Cargo.lock
  test-crates/pyo3-pure/Cargo.lock
  test-crates/sdist_with_path_dep/Cargo.lock
  test-crates/workspace-inheritance/Cargo.lock
  test-crates/workspace_with_path_dep/Cargo.lock
  tests/cmd/generate-ci.stdout
Labels: release

#1497 chore: Update some dependencies
  Cargo.lock
Labels: dependencies, rust

#1499 Update cargo-zigbuild to 0.16.1
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust

#1501 Update cargo-zigbuild to 0.16.2
  Cargo.lock
  Cargo.toml
Labels: dependencies, rust
