Repository PyO3/maturin, pull requests merged in 2024-03, with the labels that each got.

#1965 Update to Metadata 2.3 to create reliable source dist metadata
  Cargo.lock
  Cargo.toml
  Changelog.md
  src/build_context.rs
  src/build_options.rs
  src/develop.rs
  src/lib.rs
  src/main.rs
  src/metadata.rs
  src/module_writer.rs
  src/project_layout.rs
  src/source_distribution.rs
  test-crates/pyo3-mixed/Cargo.lock
  test-crates/pyo3-mixed/Cargo.toml
Labels: enhancement

#1979 Release 1.5.0
  Changelog.md
Labels: release

#2003 Release v1.5.1
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  Changelog.md
  src/ci.rs
Labels: release

#2010 Detect compiling from Linux gnu to Linux musl as cross compiling
  src/cross_compile.rs
Labels: cross-compile

#2011 generate-ci: add musllinux support
  src/ci.rs
  tests/cmd/generate-ci.stdout
Labels: github_actions, configuration
