Repository PyO3/maturin, pull requests merged in 2024-01, with the labels that each got.

#1915 Match dependency readmes by package id
  src/module_writer.rs
  src/project_layout.rs
  src/source_distribution.rs
Labels: bug

#1918 Use extension name as library name, instead of hardcoded 'native.so'
  src/module_writer.rs
Labels: bindings/cffi

#1923 Bump MSRV to 1.70
  .cirrus.yml
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  clippy.toml
Labels: breaking-change

#1926 Remove setuptools-rust and milksnake mentions from readme
  README.md
Labels: documentation

#1927 Upgrade uniffi to 0.26.0
  .cirrus.yml
  .github/workflows/test.yml
  src/templates/Cargo.toml.j2
  test-crates/uniffi-mixed/Cargo.lock
  test-crates/uniffi-mixed/Cargo.toml
  test-crates/uniffi-pure-proc-macro/Cargo.lock
  test-crates/uniffi-pure-proc-macro/Cargo.toml
  test-crates/uniffi-pure/Cargo.lock
  test-crates/uniffi-pure/Cargo.toml
Labels: bindings/uniffi
