Repository PyO3/maturin, pull requests merged in 2024-08, with the labels that each got.

#2171 Remove `install_requires` and `setup_requires` from setup.py
  setup.py
Labels: sdist

#2173 Use modern stripping option
  src/compile.rs
Labels: enhancement

#2186 Forward `cargo package --list` warnings
  src/source_distribution.rs
Labels: enhancement

#2187 Add current package context to source dist error
  src/source_distribution.rs
Labels: enhancement

#2184 Place source dist readmes next to Cargo.toml
  Changelog.md
  guide/src/contributing.md
  src/source_distribution.rs
  test-crates/readme-duplication/Cargo.lock
  test-crates/readme-duplication/Cargo.toml
  test-crates/readme-duplication/README.md
  test-crates/readme-duplication/check_installed/check_installed.py
  test-crates/readme-duplication/readme-py/Cargo.toml
  test-crates/readme-duplication/readme-py/README.md
  test-crates/readme-duplication/readme-py/pyproject.toml
  test-crates/readme-duplication/readme-py/src/lib.rs
  test-crates/readme-duplication/readme-rs/Cargo.lock
  test-crates/readme-duplication/readme-rs/Cargo.toml
  test-crates/readme-duplication/readme-rs/src/lib.rs
  tests/run.rs
Labels: bug
